services:
  - type: web
    name: zoo-solana-checkout-api
    env: node
    plan: free
    region: oregon
    branch: main
    root: "."
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    healthCheckPath: /health
